name: net_salary
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  get: 4.1.4
  cupertino_icons: ^1.0.2
  adobe_xd: ^1.1.0+1
  clay_containers: ^0.3.2
  im_stepper: ^0.1.3
  currency_text_input_formatter: ^2.0.0
  animated_size_and_fade: ^2.0.0
  auto_size_text: ^2.1.0
  keyboard_visibility: ^0.5.6
  get_storage: 2.0.2
  cached_network_image: 3.1.0
  flutter_neumorphic: 3.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf


  uses-material-design: true

